export const PLAYERS = [
    {
        name: 'ElYoya',
        gameName: 'komanche uchija',
        puuid: 'crJjL51wEoe5mBZgjHcOXVaGNc9bS2pgLCtaqsUBX0T68uor5GTaWcQERsf452a-nnESVn-INWeJjA',
        id: 'OttcybkuzOfi4hw1BixOfXsFKMrTwSeqJmMATC0OqEJbaEA',
        opgg: 'https://www.op.gg/summoners/euw/komanche%20uchiha-elite/ingame',
    },
    {
        name: 'Jojopyun',
        gameName: 'VJBYYTF0AO',
        puuid: 'J6mXlEdOZLD4xpbKNasgeojlsvegtYqCiQlVpUd4nWUQMhE4sPGk00y8MiZy4xoGkw2sAoShVNhdQw',
        id: 'yRr4vnBNz2Hc-SADDOY6TWuPw_qwtKwfyh8gfXYcBjl-RhK9eLlNJmcGBw',
        opgg: 'https://www.op.gg/summoners/euw/VJBYYTF0AO-EUW/ingame',
    },
    {
        name: 'Supa',
        gameName: 'tukaan',
        puuid: '5Nhdi4xHwPnxzxPrMrLfnWHW7rl1yqO8biT3XA0pEvQ4j6W6cwaaA5Rlvo4AWCJVqWCLVHXKo_qX1w',
        id: 'yRptmWLm8LQHsKPBFrKwY0JVSDKG-eFUmWsX-kFkTvZy4CI',
        opgg: 'https://www.op.gg/summoners/euw/tukaan-tukan/ingame',
    },
    {
        name: 'Alvaro',
        gameName: 'alvarooo',
        puuid: 'Chesqa474TEBpRI_BcrJS0JuZ4zKD-I6LxdJKWVn6qTfUMwNFDUsNUFZhzr5y51DBnezGXH8c1vWFQ',
        id: 'aXdjc9uU7ysX7tuLfbwULPiLOW1rP4qQZM8DIq1UwBgIrag',
        opgg: 'https://www.op.gg/summoners/euw/alvarooo-EUW/ingame',
    },
    {
        name: 'Myrwn',
        gameName: 'Winter arc',
        puuid: 'xYJhfncRW77PlcwzMkFCoce5es-Y_7K9bExm_eN7Njox_o6iXZ0x6b3hBqmfIiPVjVxfv4TAKOp-kA',
        id: 'NXO5MFalCTUBm4AtOhd-i5pGBaZVf5GEdZ4eNCxsNXLM8NKw',
        opgg: 'https://www.op.gg/summoners/euw/Winter%20arc-Gavi6/ingame',
    },
    {
        name: 'Razork',
        gameName: 'Razørk Activoo',
        puuid: 'D5VYtLHdGzOJEiDpDNm9JwuyDY_KsqBTPes06zoJVb4WWXYvAuHYshKZGdwmW9ofV2TZXWs4XutO1Q',
        id: 'XfIiJ6UKEcTMX6kSuzc7cF0egr-B8IhRMXelFbk2rxzpD7I',
        opgg: 'https://www.op.gg/summoners/euw/Raz%C3%B8rk%20Activoo-razzz/ingame',
    },
    {
        name: 'Oscarinin',
        gameName: 'CABALLO GANADOR',
        puuid: 'Xqph9ulTw_1EhAVCFmwLawfu_ohbTeETOu04sluTiHWYT_Tcz9N8X1nGmBgnZHqH03jSb861CZ5O9w',
        id: 'oZotwMHZDdPiGcXEdLvc-7_uzwSEeJH5KermwBsl3VEteNc',
        opgg: 'https://www.op.gg/summoners/euw/CABALLO%20GANADOR-CTANG/ingame',
    },
]