export const PLAYERS = [
    {
        name: 'ElYoya',
        gameName: 'komanche uchiha',
        puuid: '7BfJQqaZhk9eDIpIdXl9G50v4HnZU7I2nRh7LfsLnhOt5TFOZtyNkz6RE6yTWkCO0o8sHtEORl1ASA',
        id: '0Ow144eLuYozZR3CE630DyQSgn1P60ZQZImCq1xClUzNSB0',
        opgg: 'https://www.op.gg/summoners/euw/komanche%20uchiha-elite/ingame',
    },
    {
        name: 'Jojopyun',
        gameName: 'VJBYYTF0AO',
        puuid: 'Wgy6moWAIMTrj6-9AJjC8-12QGc-THpf_fuletyHmo249PspjblqZMLm0DchtbwX9hh1alnoOlRoVQ',
        id: '5-ljBMvQOnrO7dh8hwmtWKpvzZfTHiqHWhdVfzBwmjX0vnMzbYZ-ltBZew',
        opgg: 'https://www.op.gg/summoners/euw/VJBYYTF0AO-EUW/ingame',
    },
    {
        name: 'Supa',
        gameName: 'tukaan',
        puuid: 'BCaTHRBDVCu6VljqDohJe2UBQgJ7KUvcI-OyeVODICeupQ7pKVm8Q45dYJLRP6xf3SSzUYttthRIEA',
        id: 'opipK2g7KwYCTzh1jhl8T7CDoxmENxWiLUen1tcmtQkRYNM',
        opgg: 'https://www.op.gg/summoners/euw/tukaan-tukan/ingame',
    },
    {
        name: 'Alvaro',
        gameName: 'alvarooo',
        puuid: 'HirLAtggXfSmgyMwY7t4L7hXS7FCsqURQGjWhycRyknEe5MLyW92fdoUyjKAScGMYr02xIEhngioHw',
        id: 'zRL6SKFeItaJGtDwmSvwX1S5TQye_j0He0l0ev-b9HeDdN8',
        opgg: 'https://www.op.gg/summoners/euw/alvarooo-EUW/ingame',
    },
    {
        name: 'Myrwn',
        gameName: 'Winter arc',
        puuid: 'JlJmhgnApJXdd5SUBETNcdsAiLkSS4AdfWOraHvON7uKsX4faz1rMuzN-RkuYhQnG4BBlhPclMf5Lw',
        id: '7e749serD5i7fOrydzRPrzqgTe-DHlvN3SREITfnSAzO-GzN',
        opgg: 'https://www.op.gg/summoners/euw/Winter%20arc-Gavi6/ingame',
    },
    {
        name: 'Razork',
        gameName: 'Razørk Activoo',
        puuid: 'yxPaIxcqEO9Mf-EFLkx_wjkNR0uM2oVIzEDr6R6dgA6BkNO99LZmxgaVh_hQeMRxNxc77ByKtF0ktA',
        id: 'GPzKNza9IIzjfJcpn4HxIqqqO1jgsv4FryORH64xiOVxfg8',
        opgg: 'https://www.op.gg/summoners/euw/Raz%C3%B8rk%20Activoo-razzz/ingame',
    },
    {
        name: 'Oscarinin',
        gameName: 'CABALLO GANADOR',
        puuid: 'p5EMeAzYYh4kKK5CtgtuOvwF9xyskak5GbHT4MneU5uSrUJ8jJLtmbTCSjxp31A0fERydCVeXxTkrw',
        id: '50VtYh2xsjtgf5RAVvLPkD4X9Tu17XFtB85-R97Q3_fVqsg',
        opgg: 'https://www.op.gg/summoners/euw/CABALLO%20GANADOR-CTANG/ingame',
    },
    {
        name: 'Flakked',
        gameName: 'Kushala Daora',
        puuid: 'EOov7YUWD_FI4aJNvocKtITpGdhfrXdxbpkIJ77g9LnAhshyeM6UWtHRUlVsvep7RAUPIW1l0fLJtQ',
        id: 'sBgDwrcBhZ22B4NxtiJfYLKjGJxuBMQ55NNT6QTJ0ymaT8pa',
        opgg: 'https://www.op.gg/summoners/euw/Kushala%20Daora-MHVV/ingame',
    },
    {
        name: 'Caps',
        gameName: 'Dr Orange',
        puuid: 'M2OXHggFtHLNm-uG1Pga4NhFWnmlwwn416G1t_6qISLeH_v8PnB-KiTblbLCQj2oPrdA_gstZNZKmA',
        id: 'LLCEOJdIdfvteA6pzy_9yOcUA1b-d0NuIwwSPlJ9I7rWhLU',
        opgg: 'https://www.op.gg/summoners/euw/Dr%20DOrange-Caps/ingame',
    },
    {
        name: 'Skewmond',
        gameName: 'Thors Snoresson',
        puuid: 'OV7koKpjwvHkwc2WmfFr_d5gU-laTrlAWJBmgkJBmeL2rb4m4r2LBA1iQ9K2vL2KraljMRdG5_SbNw',
        id: '3jsK3sy4WRd1eGNF1fzY9N69Kcb2ev9jsYhKEgFsMzBk4asV',
        opgg: 'https://www.op.gg/summoners/euw/Thors%20Snoresson-3327/ingame',
    },
    {
        name: 'BrokenBlade',
        gameName: 'Dr BlackBerry',
        puuid: 'TCJwtWKY8CxrbjYnNvatZ_UUpXQFiX9krbAo6I1ERMuUV-sEgsiKLUqOTKGY8voottq7DRaBveGdow',
        id: 'f2VtY1Oxd7nFEbtqmLiZljFB9aeBcVY0dCNVk0FOXrQ2KTMM',
        opgg: 'https://www.op.gg/summoners/euw/Dr%20BlackBerry-Blade/ingame',
    },
    {
        name: 'Hans Sama',
        gameName: 'Dr BlackBerry',
        puuid: 'o6X5Bv0Ukp34Kz_HOxJA1ah83bNvBOaMRJo2IOpkpzBG4cQAypGc4kFjD428z_uaCOPLpjZoJJyuNQ',
        id: 'qNHHKdnpMtJ7UoPY2MXYmnmDtXgLEN5dWffFfwmAumcuAPQ',
        opgg: 'https://www.op.gg/summoners/euw/Dr%20Mango-Hans/ingame',
    },
    {
        name: 'Labrov',
        gameName: 'niudefuwuqi2007',
        puuid: 'R_souWj10vcV519UjYSrL8f7wtCEqbjK5za7gytqCaE47uYjULdcIDg0VwsNtGgIPSHBoh9xsW1aAQ',
        id: 'K7zgKYv8SjLtlq2echCabASVOi-P-16y_0viRPUAGFCjqkM',
        opgg: 'https://www.op.gg/summoners/euw/niudefuwuqi2007-8085/ingame',
    },
    {
        name: 'Caliste',
        gameName: ' KC NEXT ADKING',
        puuid: 'MPP42et9salN2NCNq6Rl9R7WIcaJOPdcMPLFKxIYUnShQbqTHsl3mNU90nhAISV1crGodOoFdCK_iA',
        id: 'yukBbsrUXmV28zhykrtaAdQitqAsayIcNj9wOEryWRM1ozuy',
        opgg: 'https://www.op.gg/summoners/euw/KC%20NEXT%20ADKING-EUW/ingame',
    },
]