export const TRACKED_PLAYERS = [
    {
        name: 'ElYoya',
        gameName: 'komanche uchiha',
        puuid: '7BfJQqaZhk9eDIpIdXl9G50v4HnZU7I2nRh7LfsLnhOt5TFOZtyNkz6RE6yTWkCO0o8sHtEORl1ASA',
        id: '0Ow144eLuYozZR3CE630DyQSgn1P60ZQZImCq1xClUzNSB0',
        opgg: 'https://www.op.gg/summoners/euw/komanche%20uchiha-elite/ingame',
    },
    {
        name: 'Jojopyun',
        gameName: 'VJBYYTF0AO',
        puuid: 'Wgy6moWAIMTrj6-9AJjC8-12QGc-THpf_fuletyHmo249PspjblqZMLm0DchtbwX9hh1alnoOlRoVQ',
        id: '5-ljBMvQOnrO7dh8hwmtWKpvzZfTHiqHWhdVfzBwmjX0vnMzbYZ-ltBZew',
        opgg: 'https://www.op.gg/summoners/euw/VJBYYTF0AO-EUW/ingame',
    },
    {
        name: 'Supa',
        gameName: 'tukaan',
        puuid: 'BCaTHRBDVCu6VljqDohJe2UBQgJ7KUvcI-OyeVODICeupQ7pKVm8Q45dYJLRP6xf3SSzUYttthRIEA',
        id: 'opipK2g7KwYCTzh1jhl8T7CDoxmENxWiLUen1tcmtQkRYNM',
        opgg: 'https://www.op.gg/summoners/euw/tukaan-tukan/ingame',
    },
    {
        name: 'Alvaro',
        gameName: 'alvarooo',
        puuid: 'HirLAtggXfSmgyMwY7t4L7hXS7FCsqURQGjWhycRyknEe5MLyW92fdoUyjKAScGMYr02xIEhngioHw',
        id: 'zRL6SKFeItaJGtDwmSvwX1S5TQye_j0He0l0ev-b9HeDdN8',
        opgg: 'https://www.op.gg/summoners/euw/alvarooo-EUW/ingame',
    },
    {
        name: 'Myrwn',
        gameName: 'Winter arc',
        puuid: 'JlJmhgnApJXdd5SUBETNcdsAiLkSS4AdfWOraHvON7uKsX4faz1rMuzN-RkuYhQnG4BBlhPclMf5Lw',
        id: '7e749serD5i7fOrydzRPrzqgTe-DHlvN3SREITfnSAzO-GzN',
        opgg: 'https://www.op.gg/summoners/euw/Winter%20arc-Gavi6/ingame',
    },
    {
        name: 'Razork',
        gameName: 'Razørk Activoo',
        puuid: 'yxPaIxcqEO9Mf-EFLkx_wjkNR0uM2oVIzEDr6R6dgA6BkNO99LZmxgaVh_hQeMRxNxc77ByKtF0ktA',
        id: 'GPzKNza9IIzjfJcpn4HxIqqqO1jgsv4FryORH64xiOVxfg8',
        opgg: 'https://www.op.gg/summoners/euw/Raz%C3%B8rk%20Activoo-razzz/ingame',
    },
    {
        name: 'Oscarinin',
        gameName: 'CABALLO GANADOR',
        puuid: 'p5EMeAzYYh4kKK5CtgtuOvwF9xyskak5GbHT4MneU5uSrUJ8jJLtmbTCSjxp31A0fERydCVeXxTkrw',
        id: '50VtYh2xsjtgf5RAVvLPkD4X9Tu17XFtB85-R97Q3_fVqsg',
        opgg: 'https://www.op.gg/summoners/euw/CABALLO%20GANADOR-CTANG/ingame',
    },
    {
        name: 'Flakked',
        gameName: 'Kushala Daora',
        puuid: 'EOov7YUWD_FI4aJNvocKtITpGdhfrXdxbpkIJ77g9LnAhshyeM6UWtHRUlVsvep7RAUPIW1l0fLJtQ',
        id: 'sBgDwrcBhZ22B4NxtiJfYLKjGJxuBMQ55NNT6QTJ0ymaT8pa',
        opgg: 'https://www.op.gg/summoners/euw/Kushala%20Daora-MHVV/ingame',
    },
    {
        name: 'Caps',
        gameName: 'Dr Orange',
        puuid: 'M2OXHggFtHLNm-uG1Pga4NhFWnmlwwn416G1t_6qISLeH_v8PnB-KiTblbLCQj2oPrdA_gstZNZKmA',
        id: 'LLCEOJdIdfvteA6pzy_9yOcUA1b-d0NuIwwSPlJ9I7rWhLU',
        opgg: 'https://www.op.gg/summoners/euw/Dr%20DOrange-Caps/ingame',
    },
    {
        name: 'Skewmond',
        gameName: 'Thors Snoresson',
        puuid: 'OV7koKpjwvHkwc2WmfFr_d5gU-laTrlAWJBmgkJBmeL2rb4m4r2LBA1iQ9K2vL2KraljMRdG5_SbNw',
        id: '3jsK3sy4WRd1eGNF1fzY9N69Kcb2ev9jsYhKEgFsMzBk4asV',
        opgg: 'https://www.op.gg/summoners/euw/Thors%20Snoresson-3327/ingame',
    },
    {
        name: 'BrokenBlade',
        gameName: 'Dr BlackBerry',
        puuid: 'TCJwtWKY8CxrbjYnNvatZ_UUpXQFiX9krbAo6I1ERMuUV-sEgsiKLUqOTKGY8voottq7DRaBveGdow',
        id: 'f2VtY1Oxd7nFEbtqmLiZljFB9aeBcVY0dCNVk0FOXrQ2KTMM',
        opgg: 'https://www.op.gg/summoners/euw/Dr%20BlackBerry-Blade/ingame',
    },
    {
        name: 'Hans Sama',
        gameName: 'Dr BlackBerry',
        puuid: 'o6X5Bv0Ukp34Kz_HOxJA1ah83bNvBOaMRJo2IOpkpzBG4cQAypGc4kFjD428z_uaCOPLpjZoJJyuNQ',
        id: 'qNHHKdnpMtJ7UoPY2MXYmnmDtXgLEN5dWffFfwmAumcuAPQ',
        opgg: 'https://www.op.gg/summoners/euw/Dr%20Mango-Hans/ingame',
    },
    {
        name: 'Labrov',
        gameName: 'niudefuwuqi2007',
        puuid: 'R_souWj10vcV519UjYSrL8f7wtCEqbjK5za7gytqCaE47uYjULdcIDg0VwsNtGgIPSHBoh9xsW1aAQ',
        id: 'K7zgKYv8SjLtlq2echCabASVOi-P-16y_0viRPUAGFCjqkM',
        opgg: 'https://www.op.gg/summoners/euw/niudefuwuqi2007-8085/ingame',
    },
    {
        name: 'Caliste',
        gameName: 'KC NEXT ADKING',
        puuid: 'MPP42et9salN2NCNq6Rl9R7WIcaJOPdcMPLFKxIYUnShQbqTHsl3mNU90nhAISV1crGodOoFdCK_iA',
        id: 'yukBbsrUXmV28zhykrtaAdQitqAsayIcNj9wOEryWRM1ozuy',
        opgg: 'https://www.op.gg/summoners/euw/KC%20NEXT%20ADKING-EUW/ingame',
    },
];

export const PLAYERS = [
    {
        name: 'ElYoya',
        puuid: '7BfJQqaZhk9eDIpIdXl9G50v4HnZU7I2nRh7LfsLnhOt5TFOZtyNkz6RE6yTWkCO0o8sHtEORl1ASA',
    },
    {
        name: 'Jojopyun',
        puuid: 'Wgy6moWAIMTrj6-9AJjC8-12QGc-THpf_fuletyHmo249PspjblqZMLm0DchtbwX9hh1alnoOlRoVQ',
    },
    {
        name: 'Supa',
        puuid: 'BCaTHRBDVCu6VljqDohJe2UBQgJ7KUvcI-OyeVODICeupQ7pKVm8Q45dYJLRP6xf3SSzUYttthRIEA',
    },
    {
        name: 'Alvaro',
        puuid: 'HirLAtggXfSmgyMwY7t4L7hXS7FCsqURQGjWhycRyknEe5MLyW92fdoUyjKAScGMYr02xIEhngioHw',
    },
    {
        name: 'Myrwn',
        puuid: 'JlJmhgnApJXdd5SUBETNcdsAiLkSS4AdfWOraHvON7uKsX4faz1rMuzN-RkuYhQnG4BBlhPclMf5Lw',
    },
    {
        name: 'Razork',
        puuid: 'yxPaIxcqEO9Mf-EFLkx_wjkNR0uM2oVIzEDr6R6dgA6BkNO99LZmxgaVh_hQeMRxNxc77ByKtF0ktA',
    },
    {
        name: 'Humanoid',
        puuid: 'J31yOqCcH3h1qCsAW15jQWFukw9L_fhgeMMS7UMCCKJ6l6e_zQW2Yst6iMVBLAcKtcb1Cdt26A7TAw',
    },
    {
        name: 'Oscarinin',
        puuid: 'p5EMeAzYYh4kKK5CtgtuOvwF9xyskak5GbHT4MneU5uSrUJ8jJLtmbTCSjxp31A0fERydCVeXxTkrw',
    },
    {
        name: 'Upset',
        puuid: 'dDvannhIAhMnMN194uTZ_yKdb3XracTF3Hkoj10O-QiIWHvKDZz2p_H6hWT1fBawwLPPEOdS8Y5uLQ',
    },
    {
        name: 'Mikyx',
        puuid: '3AB3kIdPFtaiLnGonaIW2H7C7dQDrDgIe2jxYfvTMWk5ltEL63oQ5aYm_ZIqYe8KafRxxa52DIxY9g',
    },
    {
        name: 'Flakked',
        puuid: 'EOov7YUWD_FI4aJNvocKtITpGdhfrXdxbpkIJ77g9LnAhshyeM6UWtHRUlVsvep7RAUPIW1l0fLJtQ',
    },
    {
        name: 'Kamiloo',
        puuid: 'RJ8r7MqkmVzCszKok7zQe-pW1uD6oRaX8pL3v_8tgzEwh3v_Fjrw8Q9oPmEhVGhusOySG8-sYQl3yQ',
    },
    {
        name: 'Carlsen',
        puuid: 'IAald_VcUvoZgwXuwMZ2mMgmnpiQ7F0W0wM1zgVBIUd6u6LGusNf_rmheK13q7D5hqT9cjmKvKN78A',
    },
    {
        name: 'Sheo',
        puuid: 'iNIGmrQrVQgOUKqDSahjC4SocvBFU8Urm9OJK5_QCTYhQEVOOFXbWKIPo1Z_yKKaPEH2_xvUPCFxWQ',
    },
    {
        name: 'Stend',
        puuid: 'HQkj6zRI_LDzdIjrcQohT5JGPcpzY5Y_I5RvPU4t2gu0Y8GOzIosjWn28CiQS8YBKl9avGbRPBOeEw',
    },
    {
        name: 'Caps',
        puuid: 'M2OXHggFtHLNm-uG1Pga4NhFWnmlwwn416G1t_6qISLeH_v8PnB-KiTblbLCQj2oPrdA_gstZNZKmA',
    },
    {
        name: 'Skewmond',
        puuid: 'OV7koKpjwvHkwc2WmfFr_d5gU-laTrlAWJBmgkJBmeL2rb4m4r2LBA1iQ9K2vL2KraljMRdG5_SbNw',
    },
    {
        name: 'BrokenBlade',
        puuid: 'TCJwtWKY8CxrbjYnNvatZ_UUpXQFiX9krbAo6I1ERMuUV-sEgsiKLUqOTKGY8voottq7DRaBveGdow',
    },
    {
        name: 'Hans Sama',
        puuid: 'o6X5Bv0Ukp34Kz_HOxJA1ah83bNvBOaMRJo2IOpkpzBG4cQAypGc4kFjD428z_uaCOPLpjZoJJyuNQ',
    },
    {
        name: 'Labrov',
        puuid: 'R_souWj10vcV519UjYSrL8f7wtCEqbjK5za7gytqCaE47uYjULdcIDg0VwsNtGgIPSHBoh9xsW1aAQ',
    },
    {
        name: 'Lot',
        puuid: 'ZWVlY0-k48k7UogEvfpnnqEkohBklsA5igVKwXW9fwJccXwURetBiizjmwD2MGsXu98Oj-wSu9H5wA',
    },
    {
        name: 'Closer',
        puuid: 'OH0Viy0HNSu0dMwmRyWtGjXHmzlGIW-TUoRKFcQPsmCEGZMcPcrH4ImgnHL88_jLs7htcqozdVvZXw',
    },
    {
        name: 'Jackies',
        puuid: 'DQJj7HHsXox9G6YwJ6O8f6WxdQ6ctN6JieaUtXkoSd2nZyaJY3HKwUrp_a47bMJ2kChR2hUnMho6DA',
    },
    {
        name: 'Noah',
        puuid: '1octMnwZEyhuO5QW6RfMH0Fro0Pw1C3J77jxLU20Qz8EPIGmA07c5JSoKKtd4kQcRk_guhv0CItDsA',
    },
    {
        name: 'Jun',
        puuid: 'aGq1wjyN_Xhg5TRQ84gFboo3Fp4ojom9UQDtCH96ZflFrHBauyPIPlKZB2RqKIaVQcOuv63FqqIryA',
    },
    {
        name: 'Caliste',
        puuid: 'MPP42et9salN2NCNq6Rl9R7WIcaJOPdcMPLFKxIYUnShQbqTHsl3mNU90nhAISV1crGodOoFdCK_iA',
    },
    {
        name: 'Targamas',
        puuid: 'nw4uLPuFhm2SnQ_5_00_G0pL7vZ1-PTF5VroDICem7WRfmIkZh3lAGiCIUDjQkFjy1VgUMdMRPsmNw',
    },
    {
        name: 'Vladi',
        puuid: 'UmLNRrTdXPGmgVo4_xNYKenV9gVcTh-hwc95uzQljW-ozAd2dtG1CPgmyEJN27c36eF7yqNh9es6vg',
    },
    {
        name: 'Yike',
        puuid: 'ES9ACfscRxaWWEzfsc-nbbLD61jI1vktdvTi-RMBt1WEQ1wXhDWjga0MRAlNTZL5jh6BYVyShfEdBw',
    },
    {
        name: 'Canna',
        puuid: 'APIJNARSFzwGS-1t4RWZnmxdZ42_GcSxwElmnhVIe9rWvtEy-SPUHVHtsw7rYml5vM9tDxo1JdDVJg',
    },
    {
        name: 'Adam',
        puuid: 'ftnvn2u2J7vpFKziGzpkGnndxt7Fd7jlYJZPkDc5JAjY_wIwEdIwvXLueYuNHHEVTRIaNuFvbGhR3g',
    },
    {
        name: 'Malrang',
        puuid: 'mbNiK9GIW0QOvOiOXfYgZO2SBIMLrKdwUL-8l88vORl_3weWtWTgzMjyMKHs0sJiCK1mRpc4HGnL6Q',
    },
    {
        name: 'Larssen',
        puuid: 'eMrbiTIyGe0YYYidAnvmysSzUBzfgmBlNvWJeqTruB7UFdAEGy7rmwuGiZ52wipgbjQmJfwSs5R45g',
    },
    {
        name: 'Patrik',
        puuid: 'jAFrvRfC6UzOum_3QotLIHennsMzcrMP2zIQbaGkSt4mJPtDDWcM4hoFmoOziTWmP2lnbxZV8DKifA',
    },
    {
        name: 'Execute',
        puuid: 'Unknown',
    },
    {
        name: 'JNX',
        puuid: '7NHvrg-1kzAXZpZ2x0IL-6tXq6YiZ9M71up0uGSdX3w9Fx-CxPgTKY4mHkFrW01sQsszssQrWUnnyA',
    },
    {
        name: 'Isma',
        puuid: 'X3IXOn7OiBnk4qBFL6cs3OZreEvlI6H5PEyZr_BG6rnxVnnCV5LJT_L3k25zgWNdbqoEhkB7T7uPxA',
    },
    {
        name: 'Reeker',
        puuid: 'uqa11TWtkX6nt6wF8uhraADvnXRQHBg3q4nqKbCvVwCgPUWv1e-vQfBDoKDW4fHeK3THpqY7nb2S7Q',
    },
    {
        name: 'Rahel',
        puuid: 'Unknown',
    },
    {
        name: 'Loopy',
        puuid: 'Unknown',
    },
    {
        name: 'Irrelevant',
        puuid: 'HbA2VK6n9OO4U5bA0j6uoyWtc4qPV4-pxIjnrfOaP48IzL1CA9-ucXWzxFBBfs4x9AWZROHhruQr3w',
    },
    {
        name: '113',
        puuid: 'hUAA6TC04b99stYfmkMUQCNkJtB12yI4kI-gOgW3zhpHxw16B00Ysd7_n8lPVcRYGDL_aaBPmVhFRw',
    },
    {
        name: 'nuc',
        puuid: 'MyIQycyXnSAki9lpjvuQ6DiLpSYUwGVG9l7G0ArU_tpUFnKQ7ts3k0oih5a32qh9keLPHbEITeCAsA',
    },
    {
        name: 'Ice',
        puuid: 'gN4UqllT_Qlnh58B1X7WKQzIgiJMzw1lHRgbcJqJ0217EBX_m9EPhniDwFeUGGlUsbtNQW3G7lbmOQ',
    },
    {
        name: 'Parus',
        puuid: '6JEgYoj4kWxu7qgRDnJP_8PHo9XCi_4RkCx3I3-QNeVYREqU_ktQ3gNcc53lhn8dqmHByj95fh5epA',
    },
    {
        name: 'Naak Naako',
        puuid: 'syOcZ5Nv-R7-P8TuuGS8aUa3ED7E7spaO0b8y8oGFe02yrB0kHGzaN8qCursMfJuIDYzzhsvXH89_A',
    },
    {
        name: 'Lyncas',
        puuid: 'Hw89-fQDLkGbuAcN1gJmgpPwsmCfTv7PXrW2t5823uSdkGH7d3Yah0vaXIJo_j6EMFkaaR-GVRmBJg',
    },
    {
        name: 'Czajek',
        puuid: '2j9kBcAOt0xpCGn-Tu0XzE9XXo1uVFj-zknzE65NghOCOQczYEfqp4iPmQA5CMDOm-ANikCjTHnmkg',
    },
    {
        name: 'Carzzy',
        puuid: 'SUlAzPFSyd7m127bUBbI6l9IBzWZA1P1pxJqh0ieBEt_iTQmjhEJYDFmRiyt8OHam4LeBMKW2fDe8g',
    },
    {
        name: 'Hylissang',
        puuid: '8q3KaqxYIzpaOTl8GfPImbvU6ByaKa16g47b1wIQkaiG93FuScx34zDSWR4mvn3_WcbwX8_zpaPAKQ',
    },
]

export const CHAMPIONS = [
    { name: 'Aatrox', key: '266' },
    { name: 'Ahri', key: '103' },
    { name: 'Akali', key: '84' },
    { name: 'Akshan', key: '166' },
    { name: 'Alistar', key: '12' },
    { name: 'Amumu', key: '32' },
    { name: 'Anivia', key: '34' },
    { name: 'Annie', key: '1' },
    { name: 'Aphelios', key: '523' },
    { name: 'Ashe', key: '22' },
    { name: 'Aurelion Sol', key: '136' },
    { name: 'Azir', key: '268' },
    { name: 'Bard', key: '432' },
    { name: "Bel'Veth", key: '200' },
    { name: 'Blitzcrank', key: '53' },
    { name: 'Brand', key: '63' },
    { name: 'Braum', key: '201' },
    { name: 'Caitlyn', key: '51' },
    { name: 'Camille', key: '164' },
    { name: 'Cassiopeia', key: '69' },
    { name: "Cho'Gath", key: '31' },
    { name: 'Corki', key: '42' },
    { name: 'Darius', key: '122' },
    { name: 'Diana', key: '131' },
    { name: 'Draven', key: '119' },
    { name: 'Dr. Mundo', key: '36' },
    { name: 'Ekko', key: '245' },
    { name: 'Elise', key: '60' },
    { name: 'Evelynn', key: '28' },
    { name: 'Ezreal', key: '81' },
    { name: 'Fiddlesticks', key: '9' },
    { name: 'Fiora', key: '114' },
    { name: 'Fizz', key: '105' },
    { name: 'Galio', key: '3' },
    { name: 'Gangplank', key: '41' },
    { name: 'Garen', key: '86' },
    { name: 'Gnar', key: '150' },
    { name: 'Gragas', key: '79' },
    { name: 'Graves', key: '104' },
    { name: 'Gwen', key: '887' },
    { name: 'Hecarim', key: '120' },
    { name: 'Heimerdinger', key: '74' },
    { name: 'Illaoi', key: '420' },
    { name: 'Irelia', key: '39' },
    { name: 'Ivern', key: '427' },
    { name: 'Janna', key: '40' },
    { name: 'Jarvan IV', key: '59' },
    { name: 'Jax', key: '24' },
    { name: 'Jayce', key: '126' },
    { name: 'Jhin', key: '202' },
    { name: 'Jinx', key: '222' },
    { name: "Kai'Sa", key: '145' },
    { name: 'Kalista', key: '429' },
    { name: 'Karma', key: '43' },
    { name: 'Karthus', key: '30' },
    { name: 'Kassadin', key: '38' },
    { name: 'Katarina', key: '55' },
    { name: 'Kayle', key: '10' },
    { name: 'Kayn', key: '141' },
    { name: 'Kennen', key: '85' },
    { name: "Kha'Zix", key: '121' },
    { name: 'Kindred', key: '203' },
    { name: 'Kled', key: '240' },
    { name: "Kog'Maw", key: '96' },
    { name: "K'Sante", key: '897' },
    { name: 'LeBlanc', key: '7' },
    { name: 'Lee Sin', key: '64' },
    { name: 'Leona', key: '89' },
    { name: 'Lillia', key: '876' },
    { name: 'Lissandra', key: '127' },
    { name: 'Lucian', key: '236' },
    { name: 'Lulu', key: '117' },
    { name: 'Lux', key: '99' },
    { name: 'Malphite', key: '54' },
    { name: 'Malzahar', key: '90' },
    { name: 'Maokai', key: '57' },
    { name: 'Master Yi', key: '11' },
    { name: 'Miss Fortune', key: '21' },
    { name: 'Wukong', key: '62' },
    { name: 'Mordekaiser', key: '82' },
    { name: 'Morgana', key: '25' },
    { name: 'Nami', key: '267' },
    { name: 'Nasus', key: '75' },
    { name: 'Nautilus', key: '111' },
    { name: 'Neeko', key: '518' },
    { name: 'Nidalee', key: '76' },
    { name: 'Nilah', key: '895' },
    { name: 'Nocturne', key: '56' },
    { name: 'Nunu & Willump', key: '20' },
    { name: 'Olaf', key: '2' },
    { name: 'Orianna', key: '61' },
    { name: 'Ornn', key: '516' },
    { name: 'Pantheon', key: '80' },
    { name: 'Poppy', key: '78' },
    { name: 'Pyke', key: '555' },
    { name: 'Qiyana', key: '246' },
    { name: 'Quinn', key: '133' },
    { name: 'Rakan', key: '497' },
    { name: 'Rammus', key: '33' },
    { name: "Rek'Sai", key: '421' },
    { name: 'Rell', key: '526' },
    { name: 'Renata Glasc', key: '888' },
    { name: 'Renekton', key: '58' },
    { name: 'Rengar', key: '107' },
    { name: 'Riven', key: '92' },
    { name: 'Rumble', key: '68' },
    { name: 'Ryze', key: '13' },
    { name: 'Samira', key: '360' },
    { name: 'Sejuani', key: '113' },
    { name: 'Senna', key: '235' },
    { name: 'Seraphine', key: '147' },
    { name: 'Sett', key: '875' },
    { name: 'Shaco', key: '35' },
    { name: 'Shen', key: '98' },
    { name: 'Shyvana', key: '102' },
    { name: 'Singed', key: '27' },
    { name: 'Sion', key: '14' },
    { name: 'Sivir', key: '15' },
    { name: 'Skarner', key: '72' },
    { name: 'Sona', key: '37' },
    { name: 'Soraka', key: '16' },
    { name: 'Swain', key: '50' },
    { name: 'Sylas', key: '517' },
    { name: 'Syndra', key: '134' },
    { name: 'Tahm Kench', key: '223' },
    { name: 'Taliyah', key: '163' },
    { name: 'Talon', key: '91' },
    { name: 'Taric', key: '44' },
    { name: 'Teemo', key: '17' },
    { name: 'Thresh', key: '412' },
    { name: 'Tristana', key: '18' },
    { name: 'Trundle', key: '48' },
    { name: 'Tryndamere', key: '23' },
    { name: 'Twisted Fate', key: '4' },
    { name: 'Twitch', key: '29' },
    { name: 'Udyr', key: '77' },
    { name: 'Urgot', key: '6' },
    { name: 'Varus', key: '110' },
    { name: 'Vayne', key: '67' },
    { name: 'Veigar', key: '45' },
    { name: "Vel'Koz", key: '161' },
    { name: 'Vex', key: '711' },
    { name: 'Vi', key: '254' },
    { name: 'Viego', key: '234' },
    { name: 'Viktor', key: '112' },
    { name: 'Vladimir', key: '8' },
    { name: 'Volibear', key: '106' },
    { name: 'Warwick', key: '19' },
    { name: 'Xayah', key: '498' },
    { name: 'Xerath', key: '101' },
    { name: 'Xin Zhao', key: '5' },
    { name: 'Yasuo', key: '157' },
    { name: 'Yone', key: '777' },
    { name: 'Yorick', key: '83' },
    { name: 'Yuumi', key: '350' },
    { name: 'Zac', key: '154' },
    { name: 'Zed', key: '238' },
    { name: 'Zeri', key: '221' },
    { name: 'Ziggs', key: '115' },
    { name: 'Zilean', key: '26' },
    { name: 'Zoe', key: '142' },
    { name: 'Zyra', key: '143' }
  ];
  